### ISSUE TITLE
Using ligatures (FA Pro) leads to icon conflicts

### ISSUE THREAD

**Issue by adrfantini** [duskmoon314/typst-fontawesome#11]
I'm using FA Pro and, as reported in #2, the Pro icons are used with ligatures. This leads to issues such as #10, but also to the fact that there are conflicts between the icons.

For example, trying to use an icon [`arrow-down-right`](https://fontawesome.com/icons/arrow-down-right?f=sharp&s=regular) will result in `arrow-` followed by the [`down-right`](https://fontawesome.com/icons/down-right?f=sharp&s=regular) icon.

Example result: 
![image](https://github.com/user-attachments/assets/bdad9c94-254e-4e09-8204-2cdd28627a3c)

**Comment by duskmoon314** [comment]
Wow, this is not good. 😢 

I assume the typst looks up the glyph after the line breaks, so this is also a typist/typst#2578-related issue.

**Comment by adrfantini** [comment]
> Wow, this is not good. 😢
> 
> I assume the typst looks up the glyph after the line breaks, so this is also a typist/typst#2578-related issue.

Would it be possible to use the same approach you used for the basic icons for Pro as well?

**Comment by duskmoon314** [comment]
> Would it be possible to use the same approach you used for the basic icons for Pro as well?

I just extracted the icons' names, aliases, and Unicode from the Free version's metadata.json file. If a JSON exists for the whole Pro set, the Python script can be used to generate the map.

I have come up with the idea of writing a scrapper to extract all metadata from Fontawesome's website...

**Comment by adrfantini** [comment]
> > Would it be possible to use the same approach you used for the basic icons for Pro as well?
> 
> I just extracted the icons' names, aliases, and Unicode from the Free version's metadata.json file. If a JSON exists for the whole Pro set, the Python script can be used to generate the map.
> 
> I have come up with the idea of writing a scrapper to extract all metadata from Fontawesome's website...

What info do you need to extract from the JSON? I'm not sure if there is such a file for the Pro, but there are other files which might contain the same data

**Comment by duskmoon314** [comment]
Wow, that is enough for your use case.

You can build up a dictionary from the output in this form:

```typst
#let fa-pro-icon-map = (
  "<icon-name>": "\u{<unicode>}",
)
```

> Take a look at `lib-gen.typ` for an example.

Then you can pass it to `fa-icon`:

```typst
#let fa-icon = fa-icon.with(font: "Font Awesome 6 Pro", fa-icon-map: fa-pro-icon-map)
```

After that, Unicode is used if the name can be found in the dictionary.

I think the method of extracting information from font files may lack icon aliases, but that is only gilding the lily.

Another issue that might occur is the solid version may not be found since typst treat `Font Awesome 6 Free Regular` and `Font Awesome 6 Free Solid` as two fonts.

**Comment by duskmoon314** [comment]
I haven't tested JSON before. I assume typst takes "\u{f445}" and doesn't translate it to Unicode sequence.

You can just generate a typst file and include the map:
1. Rename the JSON to typst file and use regex to replace `\\u`.
2. Add `#let fa-pro-icon-map =` to the front.
3. Include the map in your main file.

**Comment by adrfantini** [comment]
> I haven't tested JSON before. I assume typst takes "\u{f445}" and doesn't translate it to Unicode sequence.
> 
> You can just generate a typst file and include the map:
> 
> 1. Rename the JSON to typst file and use regex to replace `\\u`.
> 2. Add `#let fa-pro-icon-map =` to the front.
> 3. Include the map in your main file.

I'm unsure why my solution did not work, I assume that the escaping was incorrect? In any case, including a `.typ` file works!

Feel free to close unless you want to solve this in a more generic way

**Comment by duskmoon314** [comment]
I found that FontAwesome provides a GraphQL API for getting icon metadata. I have written a simple script to get icons of v6.6.0 and generated a typst file `lib-gen.typ` that can be found in PR #13.

Can you please help me check whether the generated typst file covers your usage? If so, we can support icons from pro sets more easily.
