### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by Athishpranav2003** [duskmoon314/typst-fontawesome#15]
![image](https://github.com/user-attachments/assets/74f5db32-4918-49ca-bb92-45a3b42d3603)
The icons seems to not render. Same issue exist in the typst.app website as well

**Comment by duskmoon314** [comment]
Could you let me know if you installed the Font Awesome fonts? The package doesn't include the font.

If you have installed the fonts, then this is an issue.

**Comment by Athishpranav2003** [comment]
![image](https://github.com/user-attachments/assets/c3e58d09-0a30-4d94-99ca-679130fb6aaf)

@duskmoon314

**Comment by duskmoon314** [comment]
I only see Free sets. `fa-github` needs the Brands set. Have you installed that one?

Also, could you provide the version of Font Awesome, typst, and your environment?

**Comment by Athishpranav2003** [comment]
@duskmoon314 
![image](https://github.com/user-attachments/assets/4dec7eb2-379b-4287-8f62-83aee63b6f83)

Fontawesome: 6.6.0
typst: 0.11.1
env: Fedora 39
