### ISSUE TITLE
fontawesome:0.4.0 broken in typst v0.12.0

### ISSUE THREAD

**Issue by jxpeng98** [duskmoon314/typst-fontawesome#16]
I tested the package via the local environment and typed the web app. I received the same message.

```
warning: unknown font family: font awesome 6 sharp duotone
   ┌─ @preview/fontawesome:0.4.0/lib-impl.typ:20:10
   │  
20 │       font: (
   │ ╭───────────^
21 │ │       "Font Awesome 6 Free" + if solid { " Solid" },
22 │ │       "Font Awesome 6 Brands",
23 │ │       // TODO: Help needed to test following fonts
   · │
27 │ │       "Font Awesome 6 Sharp Duotone" + if solid { " Solid" },
28 │ │     ),
   │ ╰─────^
```

<img width="189" alt="image" src="https://github.com/user-attachments/assets/cd668267-8834-46d6-8d3f-f4adcda4d7e8">

Typst v0.11.1 works fine.

From Typst changelog, they mentioned that:
> Setting the font to an unavailable family will now result in a warning

**Comment by duskmoon314** [comment]
This package doesn't provide the font file, so a warning would be great if the Free set is not found. However, I currently have no idea how to handle Pro sets.

**Comment by noboevbo** [comment]
Some possibilities could be:

- Splitting the fontawesome package in a pro and free version, both providing the #fa-icon function
- Appending a pro option (#let fa-icon(name, solid: false, pro: false, [...])[[...] if pro { include pro fonts in #text))
- Adding a new function #fa-icon-pro containing the pro fonts
- (my preffered one, but requires documentation): Adding a state, something like:

```typst
#let _useProFonts = state("pro-fonts", false);
#let use-pro-fonts = { _useProFronts.update(true) }

#let fa-icon(
  name,
  solid: false,
  fa-icon-map: (:),
  ..args,
) = {
  context {
    let fonts = (
      "Font Awesome 6 Free" + if solid { " Solid" },
      "Font Awesome 6 Brands",
      )
    if (_useProFonts.get()) {
      fonts.join((
         "Font Awesome 6 Pro" + if solid { " Solid" },
        "Font Awesome 6 Duotone",
        "Font Awesome 6 Sharp" + if solid { " Solid" },
        "Font Awesome 6 Sharp Duotone" + if solid { " Solid" },
      ))
    }
  text(
    font: fonts,
    // TODO: We might need to check whether this is needed
    weight: if solid { 900 } else { 400 },
    // If the name is in the map, use the unicode from the map
    // If not, pass the name and let the ligature feature handle it
    fa-icon-map.at(name, default: name),
    ..args,
  )
  }
}

```

I'm still new to typst, so there may be better ways to built the fonts array (shorthand if or something like that).

**Comment by duskmoon314** [comment]
> * (my preffered one, but requires documentation): Adding a state, something like: [main...noboevbo:typst-fontawesome:main](https://github.com/duskmoon314/typst-fontawesome/compare/main...noboevbo:typst-fontawesome:main)

Considering all the generated methods are affected by the default fonts, I agree with you. I will fix this ASAP

**Comment by noboevbo** [comment]
> > * (my preffered one, but requires documentation): Adding a state, something like: [main...noboevbo:typst-fontawesome:main](https://github.com/duskmoon314/typst-fontawesome/compare/main...noboevbo:typst-fontawesome:main)
> 
> Considering all the generated methods are affected by the default fonts, I agree with you. I will fix this ASAP

Thanks! I created a pull request, as I already implemented it to continue work without those warning messages.

**Comment by duskmoon314** [comment]
Oh, sorry. I just pushed the commit with a similar implementation and updated documents. (Though I add a co-author line) 😢

**Comment by noboevbo** [comment]
> Oh, sorry. I just pushed the commit with a similar implementation and updated documents. (Though I add a co-author line) 😢

No problem :) Thanks for the quick fix and the quick pr to the typst packages repo.
