### ISSUE TITLE
How to use Solid style icons in fontawesome

### ISSUE THREAD

**Issue by xjasonlyu** [duskmoon314/typst-fontawesome#3]
In `fontawesome` package, how can we specify solid style icons instead of regular style?

**Comment by duskmoon314** [comment]
Currently, a way to use solid style icons is by specifying the `fa-set` parameter. Like `Font Awesome 6 Brands`, solid style icons belong to `Font Awesome 6 Free Solid`. Thus, an example could be:

```typst
// Only one icon
#fa-chess-queen(fa-set: "Free Solid")

// All icons
FA_SET.update("Free Solid")
#fa-chess-queen()
...
```

A better way to achieve this is needed. But I am still trying to figure out how to implement this for now.
