### ISSUE TITLE
Package should not rely on font fallback

### ISSUE THREAD

**Issue by Enivex** [duskmoon314/typst-fontawesome#6]
Currently, the package breaks if I use `#set text(fallback: false)`.

The issue is that it relies on implicit fallback in order to do its thing. As an example
```
#fontawesome.fa-orcid()
#fontawesome.fa-phone()
```
displays tofus. If I do `#fontawesome.FA_SET.update("Brands")`, then `fa-orcid()` does work, while if I do `#fontawesome.FA_SET.update("Free Solid")` then `fa-phone()` works. Both cannot work simultaneously.

Instead of what it's currently doing, the package should specify an explicit list of fonts, and not just a single font.

**Comment by Enivex** [comment]
For the time being I just changed the definition of `fa-icon` to 
```
#let fa-icon(
  name,
  solid: true,
) = {
  text(
    font: (
      "Font Awesome 6 Brands",
      "Font Awesome 6 Free" + if solid {
        " solid"
      },
    ),
    name,
    fallback: false,
  )
}
```
Which works sufficiently well for the time being.

**Comment by duskmoon314** [comment]
Wow, I didn't notice that I can use an array of fonts as the parameter.

Cool, I will fix this ASAP.

**Comment by duskmoon314** [comment]
Thanks! I think this is fixed now.
